### ISSUE TITLE
Permit configurability of the lightwalletd server.

### ISSUE THREAD

**Issue by nuttycom** [Electric-Coin-Company/zashi#15]
## Is your feature request related to a problem? Please describe.
If the lightwalletd servers that are hard-coded into the app go down, the user has no way of using their funds. Also, some users may prefer to run their own lightwalletd servers to avoid leaking sensitive information about their transactions to a server run by a third party.

## Describe the solution you'd like
The settings screen of the application should allow the user to set their own lightwallet host and port.

**Comment by daira** [comment]
@nuttycom proposes (and I agree):
> * The wallet's current server is always stored in the format of the custom field. It can be set at the same time as the initial migration, but then should only be manually changed via the server selection screen from then on.
> * The set of options to change to is provided from a CDN-hosted file, plus the custom option.
> * If the currently selected option matches one of the options downloaded from the file, then that option should be the one marked selected, otherwise it is displayed in the custom field.
> * If no options are available from the CDN-hosted file, then just the custom field is shown.

**Comment by nuttycom** [comment]
Closed in https://github.com/Electric-Coin-Company/zashi-android/issues/1235 and https://github.com/Electric-Coin-Company/zashi-ios/issues/1028
