### ISSUE TITLE
Decide on key and database backup behaviour for 1.0

### ISSUE THREAD

**Issue by str4d** [Electric-Coin-Company/zashi#20]

**Comment by nuttycom** [comment]
We concluded:
* For iOS version 1.0, we will continue to back up the database, and the wallet startup flow will prompt the user to provide a seed phrase. We will ensure:
  * This seed phrase is validated wherever it is used in the wallet migrations.
  * The SDK provides a mechanism to validate the seed phrase to handle the case where no migrations run.
* For Android version 1.0, transferring between devices will require a full restore from seed.
