### ISSUE TITLE
Extend ECC's privacy policy to cover Zashi

### ISSUE THREAD

**Issue by daira** [Electric-Coin-Company/zashi#24]
[ECC's existing privacy policy](https://electriccoin.co/privacy-policy/) is mainly written with the website in mind.

Note, however, that it says "This policy describes how Electric Coin Company collects, uses, and shares personal information." So its stated scope is all the data ECC collects/uses/shares. In practice any data we collect in the context of the app may not be segregated from data we collect for other purposes (e.g. consider feedback, bug reports, etc. which might come either via the app or via another channel).

**Comment by true-jared** [comment]
I think we can close this ticket, right @daira ?

**Comment by nuttycom** [comment]
Completed with https://github.com/Electric-Coin-Company/zashi-android/issues/1241 and https://github.com/Electric-Coin-Company/zashi-ios/issues/940
