### ISSUE TITLE
Identify shielding transactions in the wallet UI

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi#3]
To know if the transaction is or is not a result of shield funds button tapped is tricky or for some wallet even impossible. Some extra work is needed on a code/SDK side. Then we can implement design:

https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-UI-2023-10-31?type=design&node-id=2053-16751&mode=design&t=vtcguDfa4sSEh29U-0

**Comment by daira** [comment]
@nuttycom are we sure that this does not block on #1046?

**Comment by true-jared** [comment]
Do we have this tracked for someone in the core team @daira. Could we prioritize it? @LukasKorba is ready with the implementation on the mobile side.

**Comment by true-jared** [comment]
I found the task, it is here: [zcash_client_sqlite: Identify shielding transactions in the output of the v_transactions view.](https://github.com/zcash/librustzcash/issues/1046)

**Comment by nuttycom** [comment]
@true-jared is this complete?
