### ISSUE TITLE
Consider in-app authentication requirements

### ISSUE THREAD

**Issue by ccjernigan** [Electric-Coin-Company/zashi#7]
## Is your feature request related to a problem? Please describe.
This is a followup feature for Electric-Coin-Company/zashi-android#13.  Currently, the app's encrypted storage is locked with OS-wide authentication.  Some users might prefer an additional biometric or pin prompt when opening the app.

There are different options we can consider, ranging from:
 - Requiring a recent authentication (e.g. within the last 5 minutes)
 - Requiring an unlock for each time the user cold-starts the app (effectively for each time we access the encrypted credentials)
 - Require authorization for dangerous operations only (e.g. spending or displaying the seed phrase)

## Describe the solution you'd like
Depending on the UX design, this could be enabled for all users or put behind a preference so that the additional unlock is optional.

Regardless, the implementation would leverage the Android Keystore APIs.

https://developer.android.com/training/articles/keystore#UserAuthentication

**Comment by true-jared** [comment]
More Context and Validation from the Beta Testing Group on Discord: 
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0JkQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8232ce989191ea48893dd9fc0b7bbe831f0cd60a/IMG_4243.PNG" alt="IMG_4243.PNG" />

**Comment by daira** [comment]
Released on iOS and Android.
